# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=10)),
                ('institute', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
