# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='location',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
