# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_tutor', '0002_guru_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guru',
            new_name='Tutor',
        ),
    ]
